name: Deploy Github Pages

on:
    push:
        branches: [ develop ]
        pull_request:
            branches:
                - develop

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: Build Workspace Packages
              run: |
                  npm install -g npm@7
                  npm ci
                  npm run dev
            - name: Deploy to Github Pages
              uses: JamesIves/github-pages-deploy-action@v4.3.3
              with:
                  branch: gh-pages
                  folder: ./packages/form-builder/build
                  target-folder: ${{ $GITHUB_REF_NAME }}
