name: Deploy Github Pages

on:
    push:
        branches: [ develop, feature/gh-pages ]

jobs:
    build_deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: 12.x
            - name: Build Workspace Packages
              run: |
                  npm install -g npm@7
                  npm ci
                  npm run dev
            - name: Deploy to Github Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: ./packages/form-builder/build
