name: Deploy Github Pages 📖

on:
    push:

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   name: Set env.BRANCH
                run: echo "BRANCH=$(echo $GITHUB_REF_NAME)" >> $GITHUB_ENV
            -   name: Setup Node.js
                uses: actions/setup-node@v2
                with:
                    node-version: 12.x
            -   name: Build Workspace Packages
                run: |
                    npm install -g npm@7
                    npm ci
                    cd packages/form-builder
                    npm run build
            -   name: Deploy to Github Pages
                uses: JamesIves/github-pages-deploy-action@v4.3.3
                with:
                    branch: gh-pages
                    folder: ./packages/form-builder/build
                    target-folder: ${{ env.BRANCH }}
                    commit-message: "Deploy ${{ env.BRANCH }}"
            -   uses: mshick/add-pr-comment@v1
                with:
                    repo-token: ${{ secrets.GITHUB_TOKEN }}
                    message: "A build of this branch is available at https://impress-org.github.io/givewp-next-gen/${{ env.BRANCH }}"
                    allow-repeats: false # This is the default
